wzy:
  mysql:
    db-name: com.mysql.jdbc.Driver
    db: chatgpt
    ip: 127.0.0.1
    port: 3306
    username: root
    password:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
  rocketmq:
    server: 123.249.81.202
    port: 15672
    username: admin
    password: 2630559606
