wzy:
  mysql:
    db-name: com.mysql.jdbc.Driver
    db: chatgpt
    ip: 127.0.0.1
    port: 3306
    username: root
    password:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
  rocketmq:
    server: 127.0.0.1
    port: 5672
    username: guest
    password: guest
