server:
  port: 8088

spring:
  profiles:
    #运行的环境
    active: pro
  # 数据库链接
  datasource:
    driver-class-name: ${wzy.mysql.db-name}
    url: jdbc:mysql://${wzy.mysql.ip}:${wzy.mysql.port}/${wzy.mysql.db}?useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: ${wzy.mysql.username}
    password: ${wzy.mysql.password}

  # redis配置
  redis:
    # Redis服务器地址
    host: ${wzy.redis.host}
    # Redis服务器端口号
    port: ${wzy.redis.port}
    # 设置密码
    password: ${wzy.redis.password}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间（毫秒）
    timeout: 30000ms

management:
  #actuator端口 如果不配置做默认使用上面8080端口
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        #全部端点
        include: "*"
      base-path: /actuator
  endpoint:
    shutdown:
      enabled: true #打开shutdown端点
    health:
      show-details: always #获得健康检查中所有指标的详细信息
