# 配置tomcat端口号
server:
  port: 9002

# 配置rabbitmq
spring:
  profiles:
    #运行的环境
    active: pro
  rabbitmq:
    host: ${wzy.rocketmq.server}           # rabbitMQ的ip地址
    #addresses: 192.168.150.101:8071, 192.168.150.101:8072, 192.168.150.101:8073  #集群地址
    port: ${wzy.rocketmq.port}             # 端口
    username: ${wzy.rocketmq.username}     # 账号
    password: ${wzy.rocketmq.password}     # 密码
    virtual-host: /   #虚拟机
    #publisher-confirms: true # 开启消息发送确认机制,低版本
    publisher-confirm-type: correlated # 开启消息发送确认机制

