server:
  port: 8080

spring:
  application:
    name: userservice
  profiles:
    #运行的环境
    active: pro
  # 数据库链接
  datasource:
    driver-class-name: ${wzy.mysql.db-name}
    url: jdbc:mysql://${wzy.mysql.ip}:${wzy.mysql.port}/${wzy.mysql.slave}?useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: ${wzy.mysql.username}
    password: ${wzy.mysql.password}
  cloud:
    nacos:
      server-addr: ${wzy.nacos.server}:${wzy.nacos.port}
      discovery:
        cluster-name: HZ # 集群名称

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS