server:
  port: 8080

spring:
  application:
    name: eurekaclient
  datasource:
    url: jdbc:mysql://localhost:3306/spring-wzy-slave?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true