server:
  port: 8088

spring:
  profiles:
    #运行的环境
    active: pro
  application:
    name: orderservice
  # 数据库链接
  datasource:
    driver-class-name: ${wzy.mysql.db-name}
    url: jdbc:mysql://${wzy.mysql.ip}:${wzy.mysql.port}/${wzy.mysql.master}?useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: ${wzy.mysql.username}
    password: ${wzy.mysql.password}

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:  # eureka的地址信息 --- 这里对应的是 eureka-server 的配置信息
      defaultZone: http://127.0.0.1:10086/eureka

# 给某个微服务配置负载均衡规则，这里是 eurekaclient 服务
# 可以注释掉, 这里一般采用默认的规则
eurekaclient:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则

ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - eurekaclient

