server:
  port: 8088

spring:
  datasource:
    driver-class-name: ${wzy.mysql.db-name}
    url: jdbc:mysql://${wzy.mysql.ip}:${wzy.mysql.port}/${wzy.mysql.master}?useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: ${wzy.mysql.username}
    password: ${wzy.mysql.password}
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: ${wzy.nacos.server}:${wzy.nacos.port}
    sentinel:
      transport:
        dashboard: ${wzy.sentinel.server}:${wzy.sentinel.port}
      web-context-unify: false # 关闭 context 整合

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true

feign:
  sentinel:
    enabled: true # 开启feign对sentinel的支持