server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-wzy-master?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
      web-context-unify: false # 关闭 context 整合

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true