
spring:
  application:
    name: spring-boot-event
  # 数据库链接
  # 记得修改成自己的！！！
  datasource:
    driver-class-name: ${wzy.mysql.db-name}
    url: jdbc:mysql://${wzy.mysql.ip}:${wzy.mysql.port}/${wzy.mysql.master}?useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: ${wzy.mysql.username}
    password: ${wzy.mysql.password}
server:
  port: 8088
