server:
  port: 8088

spring:
  profiles:
    #运行的环境
    active: pro
  application:
    name: orderservice
  # 数据库链接
  datasource:
    driver-class-name: ${wzy.mysql.db-name}
    url: jdbc:mysql://${wzy.mysql.ip}:${wzy.mysql.port}/${wzy.mysql.master}?useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: ${wzy.mysql.username}
    password: ${wzy.mysql.password}
  cloud:
    nacos:
      server-addr: ${wzy.nacos.server}:${wzy.nacos.port} # nacos服务地址
      discovery:
        cluster-name: HZ # 集群名称
#       namespace: 7b554f4d-02db-4a95-a2b7-67d95d203d62 # 命名空间，填ID

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
